name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd tickets && docker build -t maxnoetzold/tickets .
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker push maxnoetzold/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 58e67d27-6b9d-4ce9-9726-0e17f03e3d52
      - run: kubectl rollout restart deployment tickets-depl
